'use strict';

/**
 * Fetch the web fonts and serve them from our own origin.
 *
 *   npm run build:fonts
 *
 * Writes public/assets/fonts/*.woff2 and public/css/fonts.css, which the page
 * shells link instead of fonts.googleapis.com.
 *
 * Self-hosted rather than linked, for three reasons that all matter to a bank:
 * no third-party sees who reads the site; the type arrives in one round trip
 * to an origin the browser has already opened, instead of two to a host it has
 * not; and the page cannot end up rendering in Times because somebody else's
 * CDN is unreachable. The cost is that adding a weight means running this
 * again - which is why the output is committed.
 *
 * Only latin and latin-ext are kept. The bank publishes in English.
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'public', 'assets', 'fonts');
const CSS_OUT = path.join(ROOT, 'public', 'css', 'fonts.css');

// Asking as a current browser is what gets woff2 back rather than ttf.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// Only the weights the stylesheet actually sets. Every extra one is a file
// somebody downloads to render nothing.
const FAMILIES = [
  'Cormorant+Garamond:ital,wght@0,600;1,500',  // headlines, and the pull quote
  'Libre+Baskerville:wght@400;700',            // sub-headings and figures
  'Source+Sans+3:wght@400;500;600;700',        // body, labels, buttons, tables
  'IBM+Plex+Mono:wght@400;500',                // account numbers and amounts
];

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

function get(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': UA } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        return get(res.headers.location).then(resolve, reject);
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error(`${res.statusCode} for ${url}`));
      }
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
      return undefined;
    }).on('error', reject);
  });
}

/** A stable filename for a font file, from the family, weight and style. */
const fileNameFor = (family, weight, style, subset) =>
  `${family.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${weight}${style === 'italic' ? 'i' : ''}-${subset}.woff2`;

(async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join('&')}&display=swap`;
  const css = (await get(url)).toString('utf8');

  // Each @font-face is preceded by a /* subset */ comment, which is the only
  // place the subset name appears.
  const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)];
  if (!blocks.length) throw new Error('no @font-face blocks parsed; the response format may have changed');

  const out = [
    '/* Self-hosted web fonts. Generated by scripts/build-fonts.js - do not edit.',
    '   Run `npm run build:fonts` to add a weight or refresh the files. */',
    '',
  ];
  let downloaded = 0;
  let skipped = 0;

  for (const [, subset, face] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) { skipped += 1; continue; }

    const family = /font-family:\s*'([^']+)'/.exec(face)[1];
    const weight = /font-weight:\s*(\d+)/.exec(face)[1];
    const style = (/font-style:\s*(\w+)/.exec(face) || [, 'normal'])[1];
    const src = /url\((https:\/\/[^)]+)\)/.exec(face)[1];
    const range = (/unicode-range:\s*([^;]+);/.exec(face) || [, ''])[1].trim();

    const name = fileNameFor(family, weight, style, subset);
    const dest = path.join(OUT_DIR, name);
    if (!fs.existsSync(dest)) {
      fs.writeFileSync(dest, await get(src));
      downloaded += 1;
    }

    out.push('@font-face {');
    out.push(`  font-family: '${family}';`);
    out.push(`  font-style: ${style};`);
    out.push(`  font-weight: ${weight};`);
    out.push('  font-display: swap;');
    out.push(`  src: url('/assets/fonts/${name}') format('woff2');`);
    if (range) out.push(`  unicode-range: ${range};`);
    out.push('}');
    out.push('');
  }

  fs.writeFileSync(CSS_OUT, out.join('\n'), 'utf8');

  const bytes = fs.readdirSync(OUT_DIR)
    .filter((f) => f.endsWith('.woff2'))
    .reduce((total, f) => total + fs.statSync(path.join(OUT_DIR, f)).size, 0);

  console.log(`[fonts] ${downloaded} file(s) downloaded, ${skipped} non-latin subset(s) skipped`);
  console.log(`[fonts] ${fs.readdirSync(OUT_DIR).length} files, ${(bytes / 1024).toFixed(0)}kB total`);
  console.log('[fonts] wrote public/css/fonts.css');
})().catch((err) => {
  console.error('[fonts] failed:', err.message);
  process.exit(1);
});
